spring.application.name=spring-security-demo

#To update the default spring authentication credentials
spring.security.user.name=uma
spring.security.user.password=uma@123

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
