package org.example.controller;

import org.example.UserEntity;
import org.example.service.UserServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * @RestController - Core Spring MVC stereotype annotation that combines {@code @Controller} and {@code @ResponseBody}.
 * It registers this class as a request-handling component in the Spring Application Context.
 * Crucially, it tells Spring that the return value of every method should be serialized directly
 * into the HTTP response body (typically as JSON or XML) instead of looking for an HTML view template.
 */
@RestController
/**
 * @RequestMapping - Defines the base URL namespace for this entire controller.
 * All individual endpoint paths inside this class will be prefixed with "/user".
 * For example: http://localhost:9000/user
 */
@RequestMapping(value = "/user")
public class UserController {

    /**
     * @Autowired - Performs Dependency Injection (DI).
     * Spring searches its Bean Factory container for an instance of UserServiceImpl,
     * manages its lifecycle, and automatically wires it into this controller layer at startup.
     * Note: Injecting the concrete class (UserServiceImpl) works fine, but it is generally a best
     * practice to inject the Interface (UserService) to maintain low coupling and support mocking in unit tests.
     */
    @Autowired
    UserServiceImpl userService;

    /**
     * @PostMapping - A specialized shortcut variant of {@code @RequestMapping(method = RequestMethod.POST)}.
     * It maps HTTP POST requests hitting "/user/add" directly to this method.
     * POST is semantically used here because this endpoint is responsible for resource creation.
     * @RequestBody - Actively triggers Spring's internal HttpMessageConverter mechanism (usually backed by Jackson).
     * It reads the raw JSON payload arriving in the incoming HTTP request body, parses it, and maps the matching
     * fields directly into a freshly instantiated Java object of type UserEntity.
     * @ResponseEntity - A generic wrapper that represents the entire HTTP response.
     * It gives you absolute, programmatic control over configuring the Response Body, HTTP Status Codes, and Headers.
     */
    @PostMapping(value = "/add")
    public ResponseEntity<UserEntity> addUser(@RequestBody UserEntity userEntity) {

        // 1. Delegates business logic and data persistence layers to the service layer.
        // The service layer hashes the password and saves the entity to the MySQL database via Spring Data JPA.
        // It returns the newly persisted Entity containing its autogenerated database 'id' and hashed password.
        UserEntity userEntity1 = userService.saveUser(userEntity);

        // 2. Returns a standard HTTP response package containing:
        // - Body: The serialized JSON representation of our freshly saved userEntity1.
        // - Status Code: HttpStatus.OK (200 OK)
        // Optimization Tip: Since this is a creation endpoint, returning HttpStatus.CREATED (201 Created)
        // is technically more compliant with strict RESTful design guidelines!
        return new ResponseEntity<>(userEntity1, HttpStatus.OK);
    }

}